### PR TITLE
Language settings, Chinese translation

### PR DESCRIPTION
**Pull request by zzy-life**
I submitted, international settings, Chinese translation

### CODE REVIEW

**Comment by gaborbata** [comment]
Thanks for your contribution, I will review that, however it might take a while, as I have limited time on this project.

**Comment by gaborbata** [comment]
Nice update, however there are couple of issues based on a quick check:

* unit tests are failing
* there are typos in the language resource file
* selecting Chinese language does not seem to be working
* any modification will be dropped on restart without any notification
* you can select "Please select" from the language selector which is unhandled
* icon colors does not match the selected theme (it is black instead of dark gray or light gray)
* the license of the icon images are unknown. I would suggest to pick icons from the elementary Icons project

issues

**Comment by zzy-life** [comment]
OK, thank you for your attention. I will update it in the near future

**Comment by zzy-life** [comment]
1.Repaired unit tests，
2.Change language resource file to all lowercase，
3.Fix the problem of reading and modifying configuration files in the jar package environment，
4.Modified Icon Color Adaptation
5.Image license for non-commercial use

**Pull request closed without merging**
